In [25]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    [
        "I've been waiting for a HuggingFace course my whole life.",
        "I hate this so much!",
        "That wine is not great",
        "The IPA is tasty",
        "Subtle taste",
        "Debatable taste",
        "It could have been better"
    ]
)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9598050713539124},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455},
 {'label': 'NEGATIVE', 'score': 0.9997259974479675},
 {'label': 'POSITIVE', 'score': 0.9998561143875122},
 {'label': 'POSITIVE', 'score': 0.9990635514259338},
 {'label': 'POSITIVE', 'score': 0.9264250993728638},
 {'label': 'NEGATIVE', 'score': 0.9988137483596802}]

## Checkpoint

In [4]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

## Tokenizer

In [5]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [15]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
    "That wine is not great",
    "The IPA is tasty",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")
inputs

{'input_ids': <tf.Tensor: shape=(4, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,
            0,     0,     0,     0,     0,     0,     0],
       [  101,  2008,  4511,  2003,  2025,  2307,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0],
       [  101,  1996, 24531,  2003, 11937, 21756,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(4, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>}

## Model

In [16]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertModel: ['classifier', 'dropout_19', 'pre_classifier']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [17]:
outputs = model(inputs)
outputs

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(4, 16, 768), dtype=float32, numpy=
array([[[-0.17978   ,  0.23332772,  0.63209945, ..., -0.30166644,
          0.5008203 ,  0.14814392],
        [ 0.27577662,  0.6497117 ,  0.31997734, ..., -0.07599552,
          0.5136176 ,  0.13292289],
        [ 0.9045852 ,  0.09851328,  0.29497236, ...,  0.33519474,
         -0.14074147, -0.6464028 ],
        ...,
        [ 0.14658971,  0.5660597 ,  0.3235284 , ..., -0.3375748 ,
          0.5099783 , -0.05610824],
        [ 0.75000435,  0.04872589,  0.17380023, ...,  0.4684149 ,
          0.00296685, -0.60837525],
        [ 0.0519442 ,  0.37294796,  0.5223326 , ...,  0.35840523,
          0.6500426 , -0.38829762]],

       [[-0.293706  ,  0.72825605, -0.14972647, ..., -0.11868097,
         -1.0226723 , -0.04215714],
        [-0.22063547,  0.9383844 , -0.09512451, ..., -0.36431688,
         -0.6605215 ,  0.24069746],
        [-0.15360747,  0.89874995, -0.07276407, ..., -0.21891722,
         -0.8

## Classification head

In [18]:
from transformers import TFAutoModelForSequenceClassification
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_77']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


### Outputs logits

In [19]:
outputs.logits

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-1.5606976,  1.6122824],
       [ 4.1692314, -3.3464472],
       [ 4.545752 , -3.6566067],
       [-4.2676663,  4.5786138]], dtype=float32)>

### Post processing

In [20]:
import tensorflow as tf
predictions = tf.math.softmax(outputs.logits, axis=-1)
predictions

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[4.0195297e-02, 9.5980471e-01],
       [9.9945587e-01, 5.4418424e-04],
       [9.9972600e-01, 2.7393154e-04],
       [1.4389539e-04, 9.9985611e-01]], dtype=float32)>

In [14]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}